name: "Refresh Gitee Page"
on:
  schedule:
  - cron: "30 22 * * *"

jobs:
  reload-pages:
    runs-on: ubuntu-latest
    steps:
       - name: Build Gitee Pages
         uses: yanglbme/gitee-pages-action@main
         with:
            gitee-username: guuzaa
            gitee-password: ${{ secrets.GITEE_PASSWORD }}
            gitee-repo: ${{ secrets.REPO }}
            branch: master
