name: "Refresh Gitee Page"
on:
  schedule:
  - cron: "0 13 * * *"

jobs:
  reload-pages:
    runs-on: ubuntu-latest
    steps:
      - name: reload
        uses: mizuka-wu/gitee-pages-action@v1.0.0
        with:
          repository: guuzaa/guuzaa
          cookie: ${{ secrets.GITEE_COOKIE }}
          branch: master
